M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Thu 09 Jan 2025 09:07:48 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-09T21:07:48-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.8632Y-3.1474
X4.0541Y-3.1474
T2
X3.8514Y-3.0281
X4.0659Y-3.0281
M30
