M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Sat 11 Jan 2025 01:27:18 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-11T13:27:18-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.2402
%
G90
G05
T1
X4.1732Y-3.8976
T2
X2.2441Y-2.2835
X2.2441Y-2.7953
X2.2441Y-5.5906
M30
